// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RemoveFromCart - Use 'RemoveFromCartParams' to pass parameters into this method.
        /// </summary>
        public void RemoveFromCart()
        {
            #region Variable Declarations
            BrowserWindow uIHomePagePartsUnlimitWindow = this.UIHomePagePartsUnlimitWindow;
            HtmlHyperlink uIBrakesHyperlink = this.UIHomePagePartsUnlimitWindow.UIHomePagePartsUnlimitDocument.UIBrakesHyperlink;
            HtmlHyperlink uIDiskandPadCombo2599SHyperlink = this.UIHomePagePartsUnlimitWindow.UIBrowseProductsPartsUDocument.UIDiskandPadCombo2599SHyperlink;
            HtmlImage uIImagesproduct_brakesImage = this.UIHomePagePartsUnlimitWindow.UIProductDiskandPadComDocument.UIProductimagePane.UIImagesproduct_brakesImage;
            HtmlCell uIConstructionCell = this.UIHomePagePartsUnlimitWindow.UIProductDiskandPadComDocument.UIStoredetailsPane.UIItemTable.UIConstructionCell;
            HtmlHyperlink uIAddtoCartHyperlink = this.UIHomePagePartsUnlimitWindow.UIProductDiskandPadComDocument.UIStoredetailsPane.UIAddtoCartHyperlink;
            HtmlHyperlink uIRemoveHyperlink = this.UIHomePagePartsUnlimitWindow.UIShoppingCartPartsUnlDocument.UIRow8Pane.UIRemoveHyperlink;
            #endregion

            // Go to web page 'http://localhost:5001/'
            uIHomePagePartsUnlimitWindow.NavigateToUrl(new System.Uri(this.RemoveFromCartParams.UIHomePagePartsUnlimitWindowUrl));

            // Click 'Brakes' link
            Mouse.Click(uIBrakesHyperlink, new Point(66, 22));

            // Click 'Disk and Pad Combo 25,99 € Shop Now Disk and Pad ...' link
            Mouse.Click(uIDiskandPadCombo2599SHyperlink, new Point(271, 413));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover '/Images/product_brakes_disk-pad-combo.jpg' image at (1, 1)
            Mouse.Hover(uIImagesproduct_brakesImage, new Point(1, 1));

            // Mouse hover 'Construction' cell at (1, 1)
            Mouse.Hover(uIConstructionCell, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Add to Cart' link
            Mouse.Click(uIAddtoCartHyperlink, new Point(182, 17));

            // Click 'Remove' link
            Mouse.Click(uIRemoveHyperlink, new Point(123, 38));
        }
        
        /// <summary>
        /// RemoveFromCart2
        /// </summary>
        public void RemoveFromCart2()
        {
            #region Variable Declarations
            HtmlImage uIPartsUnlimitedlogoImage = this.UIHomePagePartsUnlimitWindow.UILoginPartsUnlimitedDocument.UIPartsUnlimitedlogoImage;
            HtmlImage uIMatteFinishRimzoomImage = this.UIHomePagePartsUnlimitWindow.UIHomePagePartsUnlimitDocument.UIHomepagePane.UIMatteFinishRimzoomImage;
            HtmlHyperlink uIAddtoCartHyperlink = this.UIHomePagePartsUnlimitWindow.UIProductMatteFinishRiDocument.UIStoredetailsPane.UIAddtoCartHyperlink;
            HtmlHyperlink uIRemoveHyperlink = this.UIHomePagePartsUnlimitWindow.UIShoppingCartPartsUnlDocument.UIRow3Pane.UIRemoveHyperlink;
            #endregion

            // Click 'Parts Unlimited logo' image
            Mouse.Click(uIPartsUnlimitedlogoImage, new Point(156, 66));

            // Click 'Matte Finish Rim zoom' image
            Mouse.Click(uIMatteFinishRimzoomImage, new Point(224, 375));

            // Click 'Add to Cart' link
            Mouse.Click(uIAddtoCartHyperlink, new Point(155, 21));

            // Click 'Remove' link
            Mouse.Click(uIRemoveHyperlink, new Point(107, 17));
        }
        
        #region Properties
        public virtual RemoveFromCartParams RemoveFromCartParams
        {
            get
            {
                if ((this.mRemoveFromCartParams == null))
                {
                    this.mRemoveFromCartParams = new RemoveFromCartParams();
                }
                return this.mRemoveFromCartParams;
            }
        }
        
        public UIHomePagePartsUnlimitWindow UIHomePagePartsUnlimitWindow
        {
            get
            {
                if ((this.mUIHomePagePartsUnlimitWindow == null))
                {
                    this.mUIHomePagePartsUnlimitWindow = new UIHomePagePartsUnlimitWindow();
                }
                return this.mUIHomePagePartsUnlimitWindow;
            }
        }
        #endregion
        
        #region Fields
        private RemoveFromCartParams mRemoveFromCartParams;
        
        private UIHomePagePartsUnlimitWindow mUIHomePagePartsUnlimitWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RemoveFromCart'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RemoveFromCartParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:5001/'
        /// </summary>
        public string UIHomePagePartsUnlimitWindowUrl = "http://localhost:5001/";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomePagePartsUnlimitWindow : BrowserWindow
    {
        
        public UIHomePagePartsUnlimitWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page – Parts Unlimited";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page – Parts Unlimited");
            this.WindowTitles.Add("Product - Blue Performance Alloy Rim – Parts Unlimited");
            this.WindowTitles.Add("Shopping Cart – Parts Unlimited");
            this.WindowTitles.Add("Browse Products – Parts Unlimited");
            this.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
            this.WindowTitles.Add("Log in – Parts Unlimited");
            this.WindowTitles.Add("Product - Matte Finish Rim – Parts Unlimited");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePagePartsUnlimitDocument UIHomePagePartsUnlimitDocument
        {
            get
            {
                if ((this.mUIHomePagePartsUnlimitDocument == null))
                {
                    this.mUIHomePagePartsUnlimitDocument = new UIHomePagePartsUnlimitDocument(this);
                }
                return this.mUIHomePagePartsUnlimitDocument;
            }
        }
        
        public UIProductBluePerformanDocument UIProductBluePerformanDocument
        {
            get
            {
                if ((this.mUIProductBluePerformanDocument == null))
                {
                    this.mUIProductBluePerformanDocument = new UIProductBluePerformanDocument(this);
                }
                return this.mUIProductBluePerformanDocument;
            }
        }
        
        public UIShoppingCartPartsUnlDocument UIShoppingCartPartsUnlDocument
        {
            get
            {
                if ((this.mUIShoppingCartPartsUnlDocument == null))
                {
                    this.mUIShoppingCartPartsUnlDocument = new UIShoppingCartPartsUnlDocument(this);
                }
                return this.mUIShoppingCartPartsUnlDocument;
            }
        }
        
        public UIBrowseProductsPartsUDocument UIBrowseProductsPartsUDocument
        {
            get
            {
                if ((this.mUIBrowseProductsPartsUDocument == null))
                {
                    this.mUIBrowseProductsPartsUDocument = new UIBrowseProductsPartsUDocument(this);
                }
                return this.mUIBrowseProductsPartsUDocument;
            }
        }
        
        public UIProductDiskandPadComDocument UIProductDiskandPadComDocument
        {
            get
            {
                if ((this.mUIProductDiskandPadComDocument == null))
                {
                    this.mUIProductDiskandPadComDocument = new UIProductDiskandPadComDocument(this);
                }
                return this.mUIProductDiskandPadComDocument;
            }
        }
        
        public UILoginPartsUnlimitedDocument UILoginPartsUnlimitedDocument
        {
            get
            {
                if ((this.mUILoginPartsUnlimitedDocument == null))
                {
                    this.mUILoginPartsUnlimitedDocument = new UILoginPartsUnlimitedDocument(this);
                }
                return this.mUILoginPartsUnlimitedDocument;
            }
        }
        
        public UIProductMatteFinishRiDocument UIProductMatteFinishRiDocument
        {
            get
            {
                if ((this.mUIProductMatteFinishRiDocument == null))
                {
                    this.mUIProductMatteFinishRiDocument = new UIProductMatteFinishRiDocument(this);
                }
                return this.mUIProductMatteFinishRiDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePagePartsUnlimitDocument mUIHomePagePartsUnlimitDocument;
        
        private UIProductBluePerformanDocument mUIProductBluePerformanDocument;
        
        private UIShoppingCartPartsUnlDocument mUIShoppingCartPartsUnlDocument;
        
        private UIBrowseProductsPartsUDocument mUIBrowseProductsPartsUDocument;
        
        private UIProductDiskandPadComDocument mUIProductDiskandPadComDocument;
        
        private UILoginPartsUnlimitedDocument mUILoginPartsUnlimitedDocument;
        
        private UIProductMatteFinishRiDocument mUIProductMatteFinishRiDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomePagePartsUnlimitDocument : HtmlDocument
    {
        
        public UIHomePagePartsUnlimitDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5001/";
            this.WindowTitles.Add("Home Page – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIPartsUnlimitedlogoImage
        {
            get
            {
                if ((this.mUIPartsUnlimitedlogoImage == null))
                {
                    this.mUIPartsUnlimitedlogoImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIPartsUnlimitedlogoImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIPartsUnlimitedlogoImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIPartsUnlimitedlogoImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Parts Unlimited logo";
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/Images/unlimited_logo.png";
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://localhost:5001/Images/unlimited_logo.png";
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/";
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.Href] = "http://localhost:5001/";
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=\"Parts Unlimited logo\" src=\"/Images/";
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIPartsUnlimitedlogoImage.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUIPartsUnlimitedlogoImage;
            }
        }
        
        public UIHomepagePane UIHomepagePane
        {
            get
            {
                if ((this.mUIHomepagePane == null))
                {
                    this.mUIHomepagePane = new UIHomepagePane(this);
                }
                return this.mUIHomepagePane;
            }
        }
        
        public HtmlHyperlink UIBrakesHyperlink
        {
            get
            {
                if ((this.mUIBrakesHyperlink == null))
                {
                    this.mUIBrakesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBrakesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBrakesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBrakesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBrakesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Brakes";
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Store/Browse";
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/Store/Browse?CategoryId=1";
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Store/Browse?CategoryId=1\"";
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "14";
                    this.mUIBrakesHyperlink.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUIBrakesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIPartsUnlimitedlogoImage;
        
        private UIHomepagePane mUIHomepagePane;
        
        private HtmlHyperlink mUIBrakesHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomepagePane : HtmlDiv
    {
        
        public UIHomepagePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "home-page";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Arrivals\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n\r\n\r\nBlue Perfor";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"home-page\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "39";
            this.WindowTitles.Add("Home Page – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIBluePerformanceAlloyImage
        {
            get
            {
                if ((this.mUIBluePerformanceAlloyImage == null))
                {
                    this.mUIBluePerformanceAlloyImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIBluePerformanceAlloyImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIBluePerformanceAlloyImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIBluePerformanceAlloyImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Blue Performance Alloy Rim zoom";
                    this.mUIBluePerformanceAlloyImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/images/product_wheel_rim-blue.jpg";
                    this.mUIBluePerformanceAlloyImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://localhost:5001/images/product_wheel_rim-blue.jpg";
                    this.mUIBluePerformanceAlloyImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/Store/Details/5";
                    this.mUIBluePerformanceAlloyImage.FilterProperties[HtmlImage.PropertyNames.Href] = "http://localhost:5001/Store/Details/5";
                    this.mUIBluePerformanceAlloyImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIBluePerformanceAlloyImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=\"Blue Performance Alloy Rim zoom\" sr";
                    this.mUIBluePerformanceAlloyImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "2";
                    this.mUIBluePerformanceAlloyImage.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUIBluePerformanceAlloyImage;
            }
        }
        
        public HtmlImage UIMatteFinishRimzoomImage
        {
            get
            {
                if ((this.mUIMatteFinishRimzoomImage == null))
                {
                    this.mUIMatteFinishRimzoomImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIMatteFinishRimzoomImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIMatteFinishRimzoomImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIMatteFinishRimzoomImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Matte Finish Rim zoom";
                    this.mUIMatteFinishRimzoomImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/images/product_wheel_rim.jpg";
                    this.mUIMatteFinishRimzoomImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://localhost:5001/images/product_wheel_rim.jpg";
                    this.mUIMatteFinishRimzoomImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/Store/Details/4";
                    this.mUIMatteFinishRimzoomImage.FilterProperties[HtmlImage.PropertyNames.Href] = "http://localhost:5001/Store/Details/4";
                    this.mUIMatteFinishRimzoomImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIMatteFinishRimzoomImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=\"Matte Finish Rim zoom\" src=\"/images";
                    this.mUIMatteFinishRimzoomImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "5";
                    this.mUIMatteFinishRimzoomImage.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUIMatteFinishRimzoomImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIBluePerformanceAlloyImage;
        
        private HtmlImage mUIMatteFinishRimzoomImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIProductBluePerformanDocument : HtmlDocument
    {
        
        public UIProductBluePerformanDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Product - Blue Performance Alloy Rim – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Details/5";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5001/Store/Details/5";
            this.WindowTitles.Add("Product - Blue Performance Alloy Rim – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UIStoredetailsPane UIStoredetailsPane
        {
            get
            {
                if ((this.mUIStoredetailsPane == null))
                {
                    this.mUIStoredetailsPane = new UIStoredetailsPane(this);
                }
                return this.mUIStoredetailsPane;
            }
        }
        #endregion
        
        #region Fields
        private UIStoredetailsPane mUIStoredetailsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIStoredetailsPane : HtmlDiv
    {
        
        public UIStoredetailsPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "store-details";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Blue Performance Alloy Rim\r\n\r\n\r\n\r\n\r\n \r\n ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"store-details\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "18";
            this.WindowTitles.Add("Product - Blue Performance Alloy Rim – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIAddtoCartHyperlink
        {
            get
            {
                if ((this.mUIAddtoCartHyperlink == null))
                {
                    this.mUIAddtoCartHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Add to Cart";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ShoppingCart/AddToCart/5";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/ShoppingCart/AddToCart/5";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn\" href=\"/ShoppingCart/AddToCar";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIAddtoCartHyperlink.WindowTitles.Add("Product - Blue Performance Alloy Rim – Parts Unlimited");
                    #endregion
                }
                return this.mUIAddtoCartHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIAddtoCartHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIShoppingCartPartsUnlDocument : HtmlDocument
    {
        
        public UIShoppingCartPartsUnlDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Shopping Cart – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/ShoppingCart";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5001/ShoppingCart";
            this.WindowTitles.Add("Shopping Cart – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UIRow1Pane UIRow1Pane
        {
            get
            {
                if ((this.mUIRow1Pane == null))
                {
                    this.mUIRow1Pane = new UIRow1Pane(this);
                }
                return this.mUIRow1Pane;
            }
        }
        
        public UIRow2Pane UIRow2Pane
        {
            get
            {
                if ((this.mUIRow2Pane == null))
                {
                    this.mUIRow2Pane = new UIRow2Pane(this);
                }
                return this.mUIRow2Pane;
            }
        }
        
        public UIRow3Pane UIRow3Pane
        {
            get
            {
                if ((this.mUIRow3Pane == null))
                {
                    this.mUIRow3Pane = new UIRow3Pane(this);
                }
                return this.mUIRow3Pane;
            }
        }
        
        public UIRow8Pane UIRow8Pane
        {
            get
            {
                if ((this.mUIRow8Pane == null))
                {
                    this.mUIRow8Pane = new UIRow8Pane(this);
                }
                return this.mUIRow8Pane;
            }
        }
        #endregion
        
        #region Fields
        private UIRow1Pane mUIRow1Pane;
        
        private UIRow2Pane mUIRow2Pane;
        
        private UIRow3Pane mUIRow3Pane;
        
        private UIRow8Pane mUIRow8Pane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRow1Pane : HtmlDiv
    {
        
        public UIRow1Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "row-1";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "1\r\n\r\n \r\n\r\n\r\nBlue Performance Alloy Rim\r\n";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "cart-item";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"cart-item\" id=\"row-1\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "26";
            this.WindowTitles.Add("Shopping Cart – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIRemoveHyperlink
        {
            get
            {
                if ((this.mUIRemoveHyperlink == null))
                {
                    this.mUIRemoveHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = " Remove ";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ShoppingCart";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/ShoppingCart#";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "remove-link btn";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"remove-link btn\" href=\"#\" data-ur";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIRemoveHyperlink.WindowTitles.Add("Shopping Cart – Parts Unlimited");
                    #endregion
                }
                return this.mUIRemoveHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIRemoveHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRow2Pane : HtmlDiv
    {
        
        public UIRow2Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "row-2";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "1\r\n\r\n \r\n\r\n\r\nDisk and Pad Combo\r\n\r\n25,99 ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "cart-item";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"cart-item\" id=\"row-2\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "26";
            this.WindowTitles.Add("Shopping Cart – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIRemoveHyperlink
        {
            get
            {
                if ((this.mUIRemoveHyperlink == null))
                {
                    this.mUIRemoveHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = " Remove ";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ShoppingCart";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/ShoppingCart#";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "remove-link btn";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"remove-link btn\" href=\"#\" data-ur";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIRemoveHyperlink.WindowTitles.Add("Shopping Cart – Parts Unlimited");
                    #endregion
                }
                return this.mUIRemoveHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIRemoveHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRow3Pane : HtmlDiv
    {
        
        public UIRow3Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "row-3";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "1\r\n\r\n \r\n\r\n\r\nMatte Finish Rim\r\n\r\n75,99 €\r";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "cart-item";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"cart-item\" id=\"row-3\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "26";
            this.WindowTitles.Add("Shopping Cart – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIRemoveHyperlink
        {
            get
            {
                if ((this.mUIRemoveHyperlink == null))
                {
                    this.mUIRemoveHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = " Remove ";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ShoppingCart";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/ShoppingCart#";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "remove-link btn";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"remove-link btn\" href=\"#\" data-ur";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIRemoveHyperlink.WindowTitles.Add("Shopping Cart – Parts Unlimited");
                    #endregion
                }
                return this.mUIRemoveHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIRemoveHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRow8Pane : HtmlDiv
    {
        
        public UIRow8Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "row-8";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "1\r\n\r\n \r\n\r\n\r\nDisk and Pad Combo\r\n\r\n25,99 ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "cart-item";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"cart-item\" id=\"row-8\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "26";
            this.WindowTitles.Add("Shopping Cart – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIRemoveHyperlink
        {
            get
            {
                if ((this.mUIRemoveHyperlink == null))
                {
                    this.mUIRemoveHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRemoveHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = " Remove ";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ShoppingCart";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/ShoppingCart#";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "remove-link btn";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"remove-link btn\" href=\"#\" data-ur";
                    this.mUIRemoveHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIRemoveHyperlink.WindowTitles.Add("Shopping Cart – Parts Unlimited");
                    #endregion
                }
                return this.mUIRemoveHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIRemoveHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIBrowseProductsPartsUDocument : HtmlDocument
    {
        
        public UIBrowseProductsPartsUDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Browse Products – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Browse";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5001/Store/Browse?CategoryId=1";
            this.WindowTitles.Add("Browse Products – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIDiskandPadCombozoomImage
        {
            get
            {
                if ((this.mUIDiskandPadCombozoomImage == null))
                {
                    this.mUIDiskandPadCombozoomImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIDiskandPadCombozoomImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIDiskandPadCombozoomImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIDiskandPadCombozoomImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Disk and Pad Combo zoom";
                    this.mUIDiskandPadCombozoomImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/images/product_brakes_disk-pad-combo.jpg";
                    this.mUIDiskandPadCombozoomImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://localhost:5001/images/product_brakes_disk-pad-combo.jpg";
                    this.mUIDiskandPadCombozoomImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/Store/Details/10";
                    this.mUIDiskandPadCombozoomImage.FilterProperties[HtmlImage.PropertyNames.Href] = "http://localhost:5001/Store/Details/10";
                    this.mUIDiskandPadCombozoomImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIDiskandPadCombozoomImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=\"Disk and Pad Combo zoom\" src=\"/imag";
                    this.mUIDiskandPadCombozoomImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "3";
                    this.mUIDiskandPadCombozoomImage.WindowTitles.Add("Browse Products – Parts Unlimited");
                    #endregion
                }
                return this.mUIDiskandPadCombozoomImage;
            }
        }
        
        public HtmlHyperlink UIDiskandPadCombo2599SHyperlink
        {
            get
            {
                if ((this.mUIDiskandPadCombo2599SHyperlink == null))
                {
                    this.mUIDiskandPadCombo2599SHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDiskandPadCombo2599SHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDiskandPadCombo2599SHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDiskandPadCombo2599SHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDiskandPadCombo2599SHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "\r\n \r\n\r\n\r\nDisk and Pad Combo\r\n\r\n25,99 €\r\n\r\n\r\n \r\n\r\n Shop Now \r\n\r\n\r\n \r\n\r\n\r\nDisk and " +
                        "Pad Combo\r\n\r\n25,99 €";
                    this.mUIDiskandPadCombo2599SHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Store/Details/10";
                    this.mUIDiskandPadCombo2599SHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Disk and Pad Combo";
                    this.mUIDiskandPadCombo2599SHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/Store/Details/10";
                    this.mUIDiskandPadCombo2599SHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIDiskandPadCombo2599SHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Disk and Pad Combo\" href=\"/Store/";
                    this.mUIDiskandPadCombo2599SHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "21";
                    this.mUIDiskandPadCombo2599SHyperlink.WindowTitles.Add("Browse Products – Parts Unlimited");
                    #endregion
                }
                return this.mUIDiskandPadCombo2599SHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIDiskandPadCombozoomImage;
        
        private HtmlHyperlink mUIDiskandPadCombo2599SHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIProductDiskandPadComDocument : HtmlDocument
    {
        
        public UIProductDiskandPadComDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Product - Disk and Pad Combo – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Details/10";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5001/Store/Details/10";
            this.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UIProductimagePane UIProductimagePane
        {
            get
            {
                if ((this.mUIProductimagePane == null))
                {
                    this.mUIProductimagePane = new UIProductimagePane(this);
                }
                return this.mUIProductimagePane;
            }
        }
        
        public UIStoredetailsPane1 UIStoredetailsPane
        {
            get
            {
                if ((this.mUIStoredetailsPane == null))
                {
                    this.mUIStoredetailsPane = new UIStoredetailsPane1(this);
                }
                return this.mUIStoredetailsPane;
            }
        }
        #endregion
        
        #region Fields
        private UIProductimagePane mUIProductimagePane;
        
        private UIStoredetailsPane1 mUIStoredetailsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIProductimagePane : HtmlDiv
    {
        
        public UIProductimagePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "product-image";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "zoom";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"zoom\" id=\"product-image\" style=\"overflow: hidden; position: relative;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "22";
            this.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIImagesproduct_brakesImage
        {
            get
            {
                if ((this.mUIImagesproduct_brakesImage == null))
                {
                    this.mUIImagesproduct_brakesImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIImagesproduct_brakesImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIImagesproduct_brakesImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIImagesproduct_brakesImage.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUIImagesproduct_brakesImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/Images/product_brakes_disk-pad-combo.jpg";
                    this.mUIImagesproduct_brakesImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://localhost:5001/Images/product_brakes_disk-pad-combo.jpg";
                    this.mUIImagesproduct_brakesImage.FilterProperties[HtmlImage.PropertyNames.Class] = "zoomImg";
                    this.mUIImagesproduct_brakesImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "class=\"zoomImg\" style=\"border: currentCo";
                    this.mUIImagesproduct_brakesImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "2";
                    this.mUIImagesproduct_brakesImage.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
                    #endregion
                }
                return this.mUIImagesproduct_brakesImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIImagesproduct_brakesImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIStoredetailsPane1 : HtmlDiv
    {
        
        public UIStoredetailsPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "store-details";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Disk and Pad Combo\r\n\r\n\r\n\r\n\r\n \r\n \r\n\r\n\r\nUS";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"store-details\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "18";
            this.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        
        public HtmlHyperlink UIAddtoCartHyperlink
        {
            get
            {
                if ((this.mUIAddtoCartHyperlink == null))
                {
                    this.mUIAddtoCartHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Add to Cart";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ShoppingCart/AddToCart/10";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/ShoppingCart/AddToCart/10";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn\" href=\"/ShoppingCart/AddToCar";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIAddtoCartHyperlink.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
                    #endregion
                }
                return this.mUIAddtoCartHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable mUIItemTable;
        
        private HtmlHyperlink mUIAddtoCartHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Disk DesignCross Drill Slotted\r\nPad Mate";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"table table-striped\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "7";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table table-striped";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIHatFinishCell
        {
            get
            {
                if ((this.mUIHatFinishCell == null))
                {
                    this.mUIHatFinishCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIHatFinishCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIHatFinishCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIHatFinishCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIHatFinishCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Hat Finish";
                    this.mUIHatFinishCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIHatFinishCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "5";
                    this.mUIHatFinishCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIHatFinishCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIHatFinishCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "11";
                    this.mUIHatFinishCell.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
                    #endregion
                }
                return this.mUIHatFinishCell;
            }
        }
        
        public HtmlCell UIConstructionCell
        {
            get
            {
                if ((this.mUIConstructionCell == null))
                {
                    this.mUIConstructionCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIConstructionCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIConstructionCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIConstructionCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIConstructionCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Construction";
                    this.mUIConstructionCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIConstructionCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "2";
                    this.mUIConstructionCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIConstructionCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIConstructionCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "5";
                    this.mUIConstructionCell.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
                    #endregion
                }
                return this.mUIConstructionCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIHatFinishCell;
        
        private HtmlCell mUIConstructionCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILoginPartsUnlimitedDocument : HtmlDocument
    {
        
        public UILoginPartsUnlimitedDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Log in – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5001/Account/Login";
            this.WindowTitles.Add("Log in – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIPartsUnlimitedlogoImage
        {
            get
            {
                if ((this.mUIPartsUnlimitedlogoImage == null))
                {
                    this.mUIPartsUnlimitedlogoImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIPartsUnlimitedlogoImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIPartsUnlimitedlogoImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIPartsUnlimitedlogoImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Parts Unlimited logo";
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/Images/unlimited_logo.png";
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://localhost:5001/Images/unlimited_logo.png";
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/";
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.Href] = "http://localhost:5001/";
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=\"Parts Unlimited logo\" src=\"/Images/";
                    this.mUIPartsUnlimitedlogoImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIPartsUnlimitedlogoImage.WindowTitles.Add("Log in – Parts Unlimited");
                    #endregion
                }
                return this.mUIPartsUnlimitedlogoImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIPartsUnlimitedlogoImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIProductMatteFinishRiDocument : HtmlDocument
    {
        
        public UIProductMatteFinishRiDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Product - Matte Finish Rim – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Details/4";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5001/Store/Details/4";
            this.WindowTitles.Add("Product - Matte Finish Rim – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UIStoredetailsPane2 UIStoredetailsPane
        {
            get
            {
                if ((this.mUIStoredetailsPane == null))
                {
                    this.mUIStoredetailsPane = new UIStoredetailsPane2(this);
                }
                return this.mUIStoredetailsPane;
            }
        }
        #endregion
        
        #region Fields
        private UIStoredetailsPane2 mUIStoredetailsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIStoredetailsPane2 : HtmlDiv
    {
        
        public UIStoredetailsPane2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "store-details";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Matte Finish Rim\r\n\r\n\r\n\r\n\r\n \r\n \r\n\r\n\r\nUSD ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"store-details\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "18";
            this.WindowTitles.Add("Product - Matte Finish Rim – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIAddtoCartHyperlink
        {
            get
            {
                if ((this.mUIAddtoCartHyperlink == null))
                {
                    this.mUIAddtoCartHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Add to Cart";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ShoppingCart/AddToCart/4";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/ShoppingCart/AddToCart/4";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn\" href=\"/ShoppingCart/AddToCar";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIAddtoCartHyperlink.WindowTitles.Add("Product - Matte Finish Rim – Parts Unlimited");
                    #endregion
                }
                return this.mUIAddtoCartHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIAddtoCartHyperlink;
        #endregion
    }
}
