// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace PartsUnlimited.CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AddToCart
        /// </summary>
        public void AddToCart()
        {
            #region Variable Declarations
            HtmlHyperlink uIBrakesHyperlink = this.UIShoppingCartPartsUnlWindow.UIShoppingCartPartsUnlDocument.UIBrakesHyperlink;
            HtmlHyperlink uIDiskandPadCombo2599SHyperlink = this.UIShoppingCartPartsUnlWindow.UIBrowseProductsPartsUDocument.UIDiskandPadCombo2599SHyperlink;
            HtmlImage uIImagesproduct_brakesImage = this.UIShoppingCartPartsUnlWindow.UIProductDiskandPadComDocument.UIProductimagePane.UIImagesproduct_brakesImage;
            HtmlCell uIDiameterCell = this.UIShoppingCartPartsUnlWindow.UIProductDiskandPadComDocument.UIStoredetailsPane.UIItemTable.UIDiameterCell;
            HtmlHyperlink uIAddtoCartHyperlink = this.UIShoppingCartPartsUnlWindow.UIProductDiskandPadComDocument.UIStoredetailsPane.UIAddtoCartHyperlink;
            #endregion

            // Click 'Brakes' link
            Mouse.Click(uIBrakesHyperlink, new Point(56, 32));

            // Click 'Disk and Pad Combo 25,99 € Shop Now Disk and Pad ...' link
            Mouse.Click(uIDiskandPadCombo2599SHyperlink, new Point(299, 198));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover '/Images/product_brakes_disk-pad-combo.jpg' image at (1, 1)
            Mouse.Hover(uIImagesproduct_brakesImage, new Point(1, 1));

            // Mouse hover 'Diameter' cell at (1, 1)
            Mouse.Hover(uIDiameterCell, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Add to Cart' link
            Mouse.Click(uIAddtoCartHyperlink, new Point(229, 27));
        }
        
        /// <summary>
        /// AddToCart2
        /// </summary>
        public void AddToCart2()
        {
            #region Variable Declarations
            HtmlHyperlink uILightingHyperlink = this.UIShoppingCartPartsUnlWindow.UIBrowseProductsPartsUDocument.UILightingHyperlink;
            HtmlImage uIHalogenHeadlights2PaImage = this.UIShoppingCartPartsUnlWindow.UIBrowseProductsPartsUDocument1.UIHalogenHeadlights2PaImage;
            HtmlImage uIImagesproduct_lightiImage = this.UIShoppingCartPartsUnlWindow.UIProductHalogenHeadliDocument.UIProductimagePane.UIImagesproduct_lightiImage;
            HtmlCell uIWiringharnessincludeCell = this.UIShoppingCartPartsUnlWindow.UIProductHalogenHeadliDocument.UIStoredetailsPane.UIItemTable.UIWiringharnessincludeCell;
            HtmlHyperlink uIAddtoCartHyperlink = this.UIShoppingCartPartsUnlWindow.UIProductHalogenHeadliDocument.UIStoredetailsPane.UIAddtoCartHyperlink;
            #endregion

            // Click 'Lighting' link
            Mouse.Click(uILightingHyperlink, new Point(57, 17));

            // Click 'Halogen Headlights (2 Pack) zoom' image
            Mouse.Click(uIHalogenHeadlights2PaImage, new Point(316, 238));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover '/Images/product_lighting_headlight.jpg' image at (1, 1)
            Mouse.Hover(uIImagesproduct_lightiImage, new Point(1, 1));

            // Mouse hover 'Wiring harness included' cell at (1, 1)
            Mouse.Hover(uIWiringharnessincludeCell, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Add to Cart' link
            Mouse.Click(uIAddtoCartHyperlink, new Point(176, 46));
        }
        
        /// <summary>
        /// ReportIt - Use 'ReportItParams' to pass parameters into this method.
        /// </summary>
        public void ReportIt()
        {
            #region Variable Declarations
            HtmlDiv uIListofOpenIncidentsLPane = this.UIListofOpenIncidentsIWindow.UIListofOpenIncidentsDocument.UIListofOpenIncidentsLPane;
            BrowserWindow uIListofOpenIncidentsIWindow = this.UIListofOpenIncidentsIWindow;
            HtmlHyperlink uIIncidentsMapHyperlink = this.UIListofOpenIncidentsIWindow.UIListofOpenIncidentsDocument.UIIncidentsMapHyperlink;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'List of Open Incidents Loading.' pane at (1, 1)
            Mouse.Hover(uIListofOpenIncidentsLPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Go to web page 'https://reportitunai.azurewebsites.net/'
            uIListofOpenIncidentsIWindow.NavigateToUrl(new System.Uri(this.ReportItParams.UIListofOpenIncidentsIWindowUrl));

            // Click 'Incidents Map' link
            Mouse.Click(uIIncidentsMapHyperlink, new Point(68, 15));
        }
        
        #region Properties
        public virtual ReportItParams ReportItParams
        {
            get
            {
                if ((this.mReportItParams == null))
                {
                    this.mReportItParams = new ReportItParams();
                }
                return this.mReportItParams;
            }
        }
        
        public UIShoppingCartPartsUnlWindow UIShoppingCartPartsUnlWindow
        {
            get
            {
                if ((this.mUIShoppingCartPartsUnlWindow == null))
                {
                    this.mUIShoppingCartPartsUnlWindow = new UIShoppingCartPartsUnlWindow();
                }
                return this.mUIShoppingCartPartsUnlWindow;
            }
        }
        
        public UIListofOpenIncidentsIWindow UIListofOpenIncidentsIWindow
        {
            get
            {
                if ((this.mUIListofOpenIncidentsIWindow == null))
                {
                    this.mUIListofOpenIncidentsIWindow = new UIListofOpenIncidentsIWindow();
                }
                return this.mUIListofOpenIncidentsIWindow;
            }
        }
        #endregion
        
        #region Fields
        private ReportItParams mReportItParams;
        
        private UIShoppingCartPartsUnlWindow mUIShoppingCartPartsUnlWindow;
        
        private UIListofOpenIncidentsIWindow mUIListofOpenIncidentsIWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ReportIt'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class ReportItParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'https://reportitunai.azurewebsites.net/'
        /// </summary>
        public string UIListofOpenIncidentsIWindowUrl = "https://reportitunai.azurewebsites.net/";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIShoppingCartPartsUnlWindow : BrowserWindow
    {
        
        public UIShoppingCartPartsUnlWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Shopping Cart – Parts Unlimited";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Shopping Cart – Parts Unlimited");
            this.WindowTitles.Add("Browse Products – Parts Unlimited");
            this.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
            this.WindowTitles.Add("Product - Halogen Headlights (2 Pack) – Parts Unlimited");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIShoppingCartPartsUnlDocument UIShoppingCartPartsUnlDocument
        {
            get
            {
                if ((this.mUIShoppingCartPartsUnlDocument == null))
                {
                    this.mUIShoppingCartPartsUnlDocument = new UIShoppingCartPartsUnlDocument(this);
                }
                return this.mUIShoppingCartPartsUnlDocument;
            }
        }
        
        public UIBrowseProductsPartsUDocument UIBrowseProductsPartsUDocument
        {
            get
            {
                if ((this.mUIBrowseProductsPartsUDocument == null))
                {
                    this.mUIBrowseProductsPartsUDocument = new UIBrowseProductsPartsUDocument(this);
                }
                return this.mUIBrowseProductsPartsUDocument;
            }
        }
        
        public UIProductDiskandPadComDocument UIProductDiskandPadComDocument
        {
            get
            {
                if ((this.mUIProductDiskandPadComDocument == null))
                {
                    this.mUIProductDiskandPadComDocument = new UIProductDiskandPadComDocument(this);
                }
                return this.mUIProductDiskandPadComDocument;
            }
        }
        
        public UIBrowseProductsPartsUDocument1 UIBrowseProductsPartsUDocument1
        {
            get
            {
                if ((this.mUIBrowseProductsPartsUDocument1 == null))
                {
                    this.mUIBrowseProductsPartsUDocument1 = new UIBrowseProductsPartsUDocument1(this);
                }
                return this.mUIBrowseProductsPartsUDocument1;
            }
        }
        
        public UIProductHalogenHeadliDocument UIProductHalogenHeadliDocument
        {
            get
            {
                if ((this.mUIProductHalogenHeadliDocument == null))
                {
                    this.mUIProductHalogenHeadliDocument = new UIProductHalogenHeadliDocument(this);
                }
                return this.mUIProductHalogenHeadliDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIShoppingCartPartsUnlDocument mUIShoppingCartPartsUnlDocument;
        
        private UIBrowseProductsPartsUDocument mUIBrowseProductsPartsUDocument;
        
        private UIProductDiskandPadComDocument mUIProductDiskandPadComDocument;
        
        private UIBrowseProductsPartsUDocument1 mUIBrowseProductsPartsUDocument1;
        
        private UIProductHalogenHeadliDocument mUIProductHalogenHeadliDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIShoppingCartPartsUnlDocument : HtmlDocument
    {
        
        public UIShoppingCartPartsUnlDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Shopping Cart – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/ShoppingCart";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5001/ShoppingCart";
            this.WindowTitles.Add("Shopping Cart – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIBrakesHyperlink
        {
            get
            {
                if ((this.mUIBrakesHyperlink == null))
                {
                    this.mUIBrakesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBrakesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBrakesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBrakesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBrakesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Brakes";
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Store/Browse";
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/Store/Browse?CategoryId=1";
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Store/Browse?CategoryId=1\"";
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "14";
                    this.mUIBrakesHyperlink.WindowTitles.Add("Shopping Cart – Parts Unlimited");
                    #endregion
                }
                return this.mUIBrakesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIBrakesHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIBrowseProductsPartsUDocument : HtmlDocument
    {
        
        public UIBrowseProductsPartsUDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Browse Products – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Browse";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5001/Store/Browse?CategoryId=1";
            this.WindowTitles.Add("Browse Products – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIDiskandPadCombo2599SHyperlink
        {
            get
            {
                if ((this.mUIDiskandPadCombo2599SHyperlink == null))
                {
                    this.mUIDiskandPadCombo2599SHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDiskandPadCombo2599SHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDiskandPadCombo2599SHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDiskandPadCombo2599SHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDiskandPadCombo2599SHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "\r\n \r\n\r\n\r\nDisk and Pad Combo\r\n\r\n25,99 €\r\n\r\n\r\n \r\n\r\n Shop Now \r\n\r\n\r\n \r\n\r\n\r\nDisk and " +
                        "Pad Combo\r\n\r\n25,99 €";
                    this.mUIDiskandPadCombo2599SHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Store/Details/10";
                    this.mUIDiskandPadCombo2599SHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Disk and Pad Combo";
                    this.mUIDiskandPadCombo2599SHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/Store/Details/10";
                    this.mUIDiskandPadCombo2599SHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIDiskandPadCombo2599SHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Disk and Pad Combo\" href=\"/Store/";
                    this.mUIDiskandPadCombo2599SHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "21";
                    this.mUIDiskandPadCombo2599SHyperlink.WindowTitles.Add("Browse Products – Parts Unlimited");
                    #endregion
                }
                return this.mUIDiskandPadCombo2599SHyperlink;
            }
        }
        
        public HtmlHyperlink UILightingHyperlink
        {
            get
            {
                if ((this.mUILightingHyperlink == null))
                {
                    this.mUILightingHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILightingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILightingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILightingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILightingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Lighting";
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Store/Browse";
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/Store/Browse?CategoryId=2";
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Store/Browse?CategoryId=2\"";
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "15";
                    this.mUILightingHyperlink.WindowTitles.Add("Browse Products – Parts Unlimited");
                    #endregion
                }
                return this.mUILightingHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIDiskandPadCombo2599SHyperlink;
        
        private HtmlHyperlink mUILightingHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIProductDiskandPadComDocument : HtmlDocument
    {
        
        public UIProductDiskandPadComDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Product - Disk and Pad Combo – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Details/10";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5001/Store/Details/10";
            this.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UIProductimagePane UIProductimagePane
        {
            get
            {
                if ((this.mUIProductimagePane == null))
                {
                    this.mUIProductimagePane = new UIProductimagePane(this);
                }
                return this.mUIProductimagePane;
            }
        }
        
        public UIStoredetailsPane UIStoredetailsPane
        {
            get
            {
                if ((this.mUIStoredetailsPane == null))
                {
                    this.mUIStoredetailsPane = new UIStoredetailsPane(this);
                }
                return this.mUIStoredetailsPane;
            }
        }
        #endregion
        
        #region Fields
        private UIProductimagePane mUIProductimagePane;
        
        private UIStoredetailsPane mUIStoredetailsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIProductimagePane : HtmlDiv
    {
        
        public UIProductimagePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "product-image";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "zoom";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"zoom\" id=\"product-image\" style=\"overflow: hidden; position: relative;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "22";
            this.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIImagesproduct_brakesImage
        {
            get
            {
                if ((this.mUIImagesproduct_brakesImage == null))
                {
                    this.mUIImagesproduct_brakesImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIImagesproduct_brakesImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIImagesproduct_brakesImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIImagesproduct_brakesImage.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUIImagesproduct_brakesImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/Images/product_brakes_disk-pad-combo.jpg";
                    this.mUIImagesproduct_brakesImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://localhost:5001/Images/product_brakes_disk-pad-combo.jpg";
                    this.mUIImagesproduct_brakesImage.FilterProperties[HtmlImage.PropertyNames.Class] = "zoomImg";
                    this.mUIImagesproduct_brakesImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "class=\"zoomImg\" style=\"border: currentCo";
                    this.mUIImagesproduct_brakesImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "2";
                    this.mUIImagesproduct_brakesImage.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
                    #endregion
                }
                return this.mUIImagesproduct_brakesImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIImagesproduct_brakesImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIStoredetailsPane : HtmlDiv
    {
        
        public UIStoredetailsPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "store-details";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Disk and Pad Combo\r\n\r\n\r\n\r\n\r\n \r\n \r\n\r\n\r\nUS";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"store-details\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "18";
            this.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        
        public HtmlHyperlink UIAddtoCartHyperlink
        {
            get
            {
                if ((this.mUIAddtoCartHyperlink == null))
                {
                    this.mUIAddtoCartHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Add to Cart";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ShoppingCart/AddToCart/10";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/ShoppingCart/AddToCart/10";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn\" href=\"/ShoppingCart/AddToCar";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIAddtoCartHyperlink.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
                    #endregion
                }
                return this.mUIAddtoCartHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable mUIItemTable;
        
        private HtmlHyperlink mUIAddtoCartHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Disk DesignCross Drill Slotted\r\nPad Mate";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"table table-striped\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "7";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table table-striped";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIDiameterCell
        {
            get
            {
                if ((this.mUIDiameterCell == null))
                {
                    this.mUIDiameterCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIDiameterCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIDiameterCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIDiameterCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIDiameterCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Diameter";
                    this.mUIDiameterCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIDiameterCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "3";
                    this.mUIDiameterCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIDiameterCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIDiameterCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "7";
                    this.mUIDiameterCell.WindowTitles.Add("Product - Disk and Pad Combo – Parts Unlimited");
                    #endregion
                }
                return this.mUIDiameterCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIDiameterCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIBrowseProductsPartsUDocument1 : HtmlDocument
    {
        
        public UIBrowseProductsPartsUDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Browse Products – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Browse";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5001/Store/Browse?CategoryId=2";
            this.WindowTitles.Add("Browse Products – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIHalogenHeadlights2PaImage
        {
            get
            {
                if ((this.mUIHalogenHeadlights2PaImage == null))
                {
                    this.mUIHalogenHeadlights2PaImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIHalogenHeadlights2PaImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIHalogenHeadlights2PaImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIHalogenHeadlights2PaImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Halogen Headlights (2 Pack) zoom";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/images/product_lighting_headlight.jpg";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://localhost:5001/images/product_lighting_headlight.jpg";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/Store/Details/1";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.Href] = "http://localhost:5001/Store/Details/1";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=\"Halogen Headlights (2 Pack) zoom\" s";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "3";
                    this.mUIHalogenHeadlights2PaImage.WindowTitles.Add("Browse Products – Parts Unlimited");
                    #endregion
                }
                return this.mUIHalogenHeadlights2PaImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIHalogenHeadlights2PaImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIProductHalogenHeadliDocument : HtmlDocument
    {
        
        public UIProductHalogenHeadliDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Product - Halogen Headlights (2 Pack) – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Details/1";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:5001/Store/Details/1";
            this.WindowTitles.Add("Product - Halogen Headlights (2 Pack) – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UIProductimagePane1 UIProductimagePane
        {
            get
            {
                if ((this.mUIProductimagePane == null))
                {
                    this.mUIProductimagePane = new UIProductimagePane1(this);
                }
                return this.mUIProductimagePane;
            }
        }
        
        public UIStoredetailsPane1 UIStoredetailsPane
        {
            get
            {
                if ((this.mUIStoredetailsPane == null))
                {
                    this.mUIStoredetailsPane = new UIStoredetailsPane1(this);
                }
                return this.mUIStoredetailsPane;
            }
        }
        #endregion
        
        #region Fields
        private UIProductimagePane1 mUIProductimagePane;
        
        private UIStoredetailsPane1 mUIStoredetailsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIProductimagePane1 : HtmlDiv
    {
        
        public UIProductimagePane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "product-image";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "zoom";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"zoom\" id=\"product-image\" style=\"overflow: hidden; position: relative;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "22";
            this.WindowTitles.Add("Product - Halogen Headlights (2 Pack) – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIImagesproduct_lightiImage
        {
            get
            {
                if ((this.mUIImagesproduct_lightiImage == null))
                {
                    this.mUIImagesproduct_lightiImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIImagesproduct_lightiImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIImagesproduct_lightiImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIImagesproduct_lightiImage.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUIImagesproduct_lightiImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/Images/product_lighting_headlight.jpg";
                    this.mUIImagesproduct_lightiImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://localhost:5001/Images/product_lighting_headlight.jpg";
                    this.mUIImagesproduct_lightiImage.FilterProperties[HtmlImage.PropertyNames.Class] = "zoomImg";
                    this.mUIImagesproduct_lightiImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "class=\"zoomImg\" style=\"border: currentCo";
                    this.mUIImagesproduct_lightiImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "2";
                    this.mUIImagesproduct_lightiImage.WindowTitles.Add("Product - Halogen Headlights (2 Pack) – Parts Unlimited");
                    #endregion
                }
                return this.mUIImagesproduct_lightiImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIImagesproduct_lightiImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIStoredetailsPane1 : HtmlDiv
    {
        
        public UIStoredetailsPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "store-details";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Halogen Headlights (2 Pack)\r\n\r\n\r\n\r\n\r\n \r\n";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"store-details\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "18";
            this.WindowTitles.Add("Product - Halogen Headlights (2 Pack) – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UIItemTable1 UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable1(this);
                }
                return this.mUIItemTable;
            }
        }
        
        public HtmlHyperlink UIAddtoCartHyperlink
        {
            get
            {
                if ((this.mUIAddtoCartHyperlink == null))
                {
                    this.mUIAddtoCartHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Add to Cart";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ShoppingCart/AddToCart/1";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:5001/ShoppingCart/AddToCart/1";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn\" href=\"/ShoppingCart/AddToCar";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIAddtoCartHyperlink.WindowTitles.Add("Product - Halogen Headlights (2 Pack) – Parts Unlimited");
                    #endregion
                }
                return this.mUIAddtoCartHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable1 mUIItemTable;
        
        private HtmlHyperlink mUIAddtoCartHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemTable1 : HtmlTable
    {
        
        public UIItemTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Light SourceHalogen\r\nAssembly RequiredYe";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"table table-striped\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "8";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table table-striped";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Product - Halogen Headlights (2 Pack) – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIWiringharnessincludeCell
        {
            get
            {
                if ((this.mUIWiringharnessincludeCell == null))
                {
                    this.mUIWiringharnessincludeCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIWiringharnessincludeCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIWiringharnessincludeCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIWiringharnessincludeCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIWiringharnessincludeCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Wiring harness included";
                    this.mUIWiringharnessincludeCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIWiringharnessincludeCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "5";
                    this.mUIWiringharnessincludeCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIWiringharnessincludeCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIWiringharnessincludeCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "11";
                    this.mUIWiringharnessincludeCell.WindowTitles.Add("Product - Halogen Headlights (2 Pack) – Parts Unlimited");
                    #endregion
                }
                return this.mUIWiringharnessincludeCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIWiringharnessincludeCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIListofOpenIncidentsIWindow : BrowserWindow
    {
        
        public UIListofOpenIncidentsIWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "List of Open Incidents";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("List of Open Incidents");
            this.WindowTitles.Add("https://reportitunai.azurewebsites.net/");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIListofOpenIncidentsDocument UIListofOpenIncidentsDocument
        {
            get
            {
                if ((this.mUIListofOpenIncidentsDocument == null))
                {
                    this.mUIListofOpenIncidentsDocument = new UIListofOpenIncidentsDocument(this);
                }
                return this.mUIListofOpenIncidentsDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIListofOpenIncidentsDocument mUIListofOpenIncidentsDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIListofOpenIncidentsDocument : HtmlDocument
    {
        
        public UIListofOpenIncidentsDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "List of Open Incidents";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://reportitunai.azurewebsites.net/";
            this.WindowTitles.Add("List of Open Incidents");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIListofOpenIncidentsLPane
        {
            get
            {
                if ((this.mUIListofOpenIncidentsLPane == null))
                {
                    this.mUIListofOpenIncidentsLPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIListofOpenIncidentsLPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIListofOpenIncidentsLPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIListofOpenIncidentsLPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "List of Open Incidents\r\n\r\n\r\n\r\n\r\nLoading.";
                    this.mUIListofOpenIncidentsLPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIListofOpenIncidentsLPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "row";
                    this.mUIListofOpenIncidentsLPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"row\"";
                    this.mUIListofOpenIncidentsLPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "7";
                    this.mUIListofOpenIncidentsLPane.WindowTitles.Add("List of Open Incidents");
                    #endregion
                }
                return this.mUIListofOpenIncidentsLPane;
            }
        }
        
        public HtmlHyperlink UIIncidentsMapHyperlink
        {
            get
            {
                if ((this.mUIIncidentsMapHyperlink == null))
                {
                    this.mUIIncidentsMapHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIIncidentsMapHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIIncidentsMapHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIIncidentsMapHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIIncidentsMapHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Incidents Map";
                    this.mUIIncidentsMapHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Citizen/Map";
                    this.mUIIncidentsMapHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIIncidentsMapHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://reportitunai.azurewebsites.net/Citizen/Map";
                    this.mUIIncidentsMapHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn btn-info btn-lg";
                    this.mUIIncidentsMapHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn btn-info btn-lg\" href=\"/Citiz";
                    this.mUIIncidentsMapHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "7";
                    this.mUIIncidentsMapHyperlink.WindowTitles.Add("List of Open Incidents");
                    #endregion
                }
                return this.mUIIncidentsMapHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIListofOpenIncidentsLPane;
        
        private HtmlHyperlink mUIIncidentsMapHyperlink;
        #endregion
    }
}
